### ISSUE TITLE
ArgumentError: wrong number of arguments (2 for 1)

### ISSUE THREAD

**Issue by kenips** [rails/protected_attributes#12]
In `lib/active_record/mass_assignment_security/core.rb` line 15:

```
assign_attributes(attributes, options) if attributes
```

raises `ArgumentError: wrong number of arguments (2 for 1)`

as `assign_attributes` only takes one argument as per https://github.com/rails/rails/blob/master/activerecord/lib/active_record/attribute_assignment.rb#L14

**Comment by Adam262** [comment]
Agree with @chancancode. Just defining `protected_attributes` before `attr_encrypted` in our Gemfile fixed it for us. With a comment to explain why the hell we need to do this! 😄
