### ISSUE TITLE
unhandled dependency on railties

### ISSUE THREAD

**Issue by andrewpcone** [rails/protected_attributes#57]
`protected_attributes` depends on `railties` if `Rails` is defined:
6886ec7b4c2431e5524e0b21088a873935acd795

This presumably is meant to test whether all of the `rails` gem is installed, which would guarantee `railties` was too. Unfortunately, there exist gmes that define `Rails`, but don't require `railtie`. I happen to be using one.

It seems we should specifically test whether `Rails::Railtie` is defined.

**Comment by carlosantoniodasilva** [comment]
People should not be defining `Rails` on their gems :disappointed: , anyway I'm fine changing the check to be on `Rails::Railtie`.

**Comment by matthewd** [comment]
@carlosantoniodasilva to be fair, "people" in this context is actually [us](https://github.com/rails/rails-html-sanitizer/blob/master/lib/rails/html/sanitizer.rb#L1).

**Comment by carlosantoniodasilva** [comment]
Indeed you're right @matthewd , I just don't expect anyone using that outside of Rails (but who knows, right?). I wonder how many places only check for `defined? Rails` out there, though :). But lets change our side to always check for `Railtie` as well, it seems the safer thing to do.

**Comment by matthewd** [comment]
See also: https://github.com/rails/rails-html-sanitizer/issues/26#issuecomment-67885679

**Comment by andrewpcone** [comment]
FWIW, I’ve used the html sanitizer outside of Rails, though that isn’t what caused the issue here.
—AC
