### ISSUE TITLE
undefined method `options_for_through_record'

### ISSUE THREAD

**Issue by covalsoest** [rails/protected_attributes#75]
After upgrade I got:

protected_attributes-1.1.1/lib/active_record/mass_assignment_security/associations.rb:96:in `<class:HasManyThroughAssociation>': undefined method `options_for_through_record' for class `ActiveRecord::Associations::HasManyThroughAssociation' (NameError)

**Comment by rafaelfranca** [comment]
Could you give more information? Which version of Rails are you using? What are you trying to do?

**Comment by covalsoest** [comment]
Thanks for the quick response. It's working ok now (updated to version 1.1.3)

I did a bundle update and the gem updated from 1.0.8 to 1.1.1:

gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb
gems/protected_attributes-1.1.1/lib/active_record/mass_assignment_security/associations.rb

Gems included by the bundle after upgrade are:
  * actionmailer (4.1.0)
  * actionpack (4.1.0)
  * actionview (4.1.0)
  * activeadmin (1.0.0.pre1 539fa4b)
  * activemodel (4.1.0)
  * activerecord (4.1.0)
  * activesupport (4.1.0)
  * arbre (1.0.3 239e811)
  * arel (5.0.1.20140414130214)
  * autoprefixer-rails (5.2.1)
  * bcrypt (3.1.10)
  * bootstrap-sass (3.3.5)
  * bootstrap_form (2.3.0)
  * bourbon (3.2.4)
  * builder (3.2.2)
  * bundler (1.10.5)
  * coffee-rails (4.0.1)
  * coffee-script (2.4.1)
  * coffee-script-source (1.9.1.1)
  * devise (3.5.1)
  * erubis (2.7.0)
  * execjs (2.5.2)
  * font-awesome-rails (4.3.0.0)
  * formtastic (3.1.3)
  * formtastic_i18n (0.4.1)
  * friendly_id (5.1.0)
  * has_scope (0.6.0)
  * hike (1.2.3)
  * i18n (0.7.0)
  * inherited_resources (1.6.0)
  * jbuilder (2.3.1)
  * jquery-rails (3.1.3)
  * jquery-turbolinks (2.1.0)
  * jquery-ui-rails (5.0.5)
  * json (1.8.3)
  * kaminari (0.16.3)
  * mail (2.5.4)
  * metamagic (3.1.7)
  * mime-types (1.25.1)
  * minitest (5.7.0)
  * multi_json (1.11.2)
  * mysql2 (0.3.18)
  * orm_adapter (0.5.0)
  * pivot_table (0.5.0)
  * polyamorous (1.2.0)
  * polyglot (0.3.5)
  * protected_attributes (1.1.1)
  * rack (1.5.5)
  * rack-test (0.6.3)
  * rails (4.1.0)
  * railties (4.1.0)
  * rake (10.4.2)
  * ransack (1.6.6)
  * rdoc (4.2.0)
  * responders (1.1.2)
  * sass (3.2.19)
  * sass-rails (4.0.5)
  * sdoc (0.4.1)
  * sprockets (2.11.0)
  * sprockets-rails (2.3.2)
  * sqlite3 (1.3.10)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (1.4.1)
  * treetop (1.4.15)
  * turbolinks (2.5.3)
  * tzinfo (1.2.2)
  * uglifier (2.7.1)
  * warden (1.2.3)
