### ISSUE TITLE
incompatible with Rails 5

### ISSUE THREAD

**Issue by orinix** [rails/protected_attributes#86]
.build function is broken in rails5 due to something in protect_attributes. Hopefully not hard to fix. Below is some sample code to cause the error and the full trace.

    > @item = ItemType.new
    => #<ItemType id: nil, name: nil, .... >
    > @item.item_abilities
    => #<ActiveRecord::Associations::CollectionProxy []>
    > @item.item_abilities.build
    ArgumentError: wrong number of arguments (given 2, expected 0..1)
    from /var/lib/gems/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/core.rb:312:in `initialize'
    from /var/lib/gems/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/inheritance.rb:65:in `new'
    from /var/lib/gems/2.3.0/gems/activerecord-5.0.0.rc2/lib/active_record/inheritance.rb:65:in `new'
    from /var/lib/gems/2.3.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/reflection.rb:8:in `build_association'
    from /var/lib/gems/2.3.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/associations.rb:7:in `build_record'
    from /var/lib/gems/2.3.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/associations.rb:25:in `build'
    from /var/lib/gems/2.3.0/gems/protected_attributes-1.1.3/lib/active_record/mass_assignment_security/associations.rb:64:in `build'
    from (irb):2
    from /var/lib/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/console.rb:65:in `start'
    from /var/lib/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/console_helper.rb:9:in `start'
    from /var/lib/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/commands_tasks.rb:78:in `console'
    from /var/lib/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    from /var/lib/gems/2.3.0/gems/railties-5.0.0.rc2/lib/rails/commands.rb:18:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'

**Comment by rafaelfranca** [comment]
Like stated in the README and in the rails 4.0 release notes, this gem do not support rails 5 and will not.

**Comment by gregblass** [comment]
Ough. Time to pay the piper!
