### ISSUE TITLE
Bugfixes in master are not yet released

### ISSUE THREAD

**Issue by mru2** [rails/protected_attributes#91]
Hi,

We are in the process of migrating our app from Rails 4.0 to Rails 4.1

We encountered the #77 issue, which was fixed in master by the #81 PR

We could require the master branch, but we would rather depend on a stable gem version.

Are you planning to release a new version of the gem soon ?

Thanks!

**Comment by westonganger** [comment]
Use my maintained gem `protected_attributes_continued` https://github.com/westonganger/protected_attributes_continued

**Comment by rafaelfranca** [comment]
@westonganger do you understand that you might be doing a disservice for the community? This gem doesn't support Rails 5 for a really good reason, that is to improve security of the applications. Maintaining it for Rails 5 in my opinion will hurt more than help.

**Comment by westonganger** [comment]
I understand it shouldnt be used if it doesnt have to. But some legacy apps simply do not care to update this portion of their code but still want to have support for Rails 5+.

**Comment by rafaelfranca** [comment]
> But some legacy apps simply do not care to update this portion of their code

They really should. Since this code is MIT there is nothing I can do about your forking and adding support, but please don't come to the issue tracker recommend people to use it, even more in an issue that is not related to it.

**Comment by rafaelfranca** [comment]
1.1.4 was released.
