### ISSUE TITLE
protected_attributes is not capatible with rails 5.2.3 with ruby 2..6.3

### ISSUE THREAD

**Issue by ashutoshpith** [rails/protected_attributes#95]
Bundler could not find compatible versions for gem "activemodel":
  In snapshot (Gemfile.lock):
    activemodel (= 5.2.3)

  In Gemfile:
    draper was resolved to 3.1.0, which depends on
      activemodel-serializers-xml (>= 1.0) was resolved to 1.0.2, which depends on
        activemodel (> 5.x)

    protected_attributes was resolved to 1.0.2, which depends on
      activemodel (>= 4.0.0.beta, < 5.0)

    rails (~> 5.2.3) was resolved to 5.2.3, which depends on
      activemodel (= 5.2.3)

    web-console (>= 3.3.0) was resolved to 3.7.0, which depends on
      activemodel (>= 5.0)
is there any other way to make compatible it with rails 5.2.3 to access attrtibutes

**Comment by rafaelfranca** [comment]
No. This gem doesn't support Rails 5 and will not support.
